server:
  port: 9015

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useSSL=false
    username: root
    password: subte147
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
auth:
  app:
    jwtCookieName: auth
    jwtSecret: ${SecretKey}
    jwtExpirationMs: 96400000
    jwtRefresh: 2592000000