global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
# - "first_rules.yml"

scrape_configs:
  - job_name: 'jwt-auth'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['jwt-auth-service:8080']
    scrape_interval: 10s
    labels:
      application: 'jwt-auth'
      environment: 'production'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']